### ISSUE TITLE
Custom backend URL

### ISSUE THREAD

**Issue by ghost** [nextseto/Players-iOS#1]
Great project, works without any problem on my iPad 10.5.
However, the backend url seem to be hardcoded into the source code (Inside cloud.swift) without any way of setting it up inside the app, so by default your (I guess?) backend server is used. 

Would it be possible to implement some simple configuration method to set a custom backend url when starting the app? 

And also as security meausare maybe remove your own backend url from the source code (+ old commits) so that Google don't ban your server ip/account. (Since they seem to hate third-party Youtube clients, especially to iOS)

**Comment by nxbyte** [comment]
Hi @goyoghurt 
Thanks for trying this out.

As of commit https://github.com/nextseto/Players-iOS/commit/512ec36de208eeed5285a8c648c4a348230809a6 anyone can now not only define their own backend url but also modify it during the app's runtime. In addition, I'm also using Active Compilation Conditions (new in Xcode 8) so anyone can test multiple versions of a given backend for their own development.
